---
- hosts: localhost
  tasks:
  - include_role:
      name: extra_debian_repo
    vars:
      key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      repo: "deb https://deb.nodesource.com/node_0.12 {{ ansible_distribution_release }} main"
      repo_source: node
